/* Generated by Together */

public class MetaClassIntrospector {
    /**
     * @label deserializes via 
     */
    private MetaClassIO lnkMetaClassIO;

    /**
     * @label discovers 
     */
    private ClassDescriptor lnkClassDescriptor;
}
