/* Generated by Together */

public class FieldDescriptor extends FeatureDescriptor {
    /**
     * @clientCardinality *
     * @supplierCardinality 0
     * @link aggregationByValue 
     */
    private ClassDescriptor lnkClassDescriptor1;
}
