/* Generated by Together */

public class MethodDescriptor extends FeatureDescriptor {
    /**
     * @clientCardinality *
     * @supplierCardinality 0
     * @link aggregationByValue 
     */
    private ClassDescriptor lnkClassDescriptor;
}
